# Generated by Django 3.1.1 on 2020-10-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='email',
            field=models.EmailField(help_text='Enter your student email provided by KUET', max_length=50, unique=True),
        ),
    ]
